In [3]:
import pandas as pd
data = pd.read_json('cladder.json')
data = data.dropna().reset_index(drop=True)

#create column "formal_form" and "graph" that holds the value corresponding to the key "formal_form" at the dict inside column "meta"

data = data.assign(formal_form = lambda x: (x['meta']))
df = data['formal_form'].apply(lambda x: (x.get("formal_form")))
data['formal_form'] = df

data = data.assign(graph = lambda x: (x['reasoning']))
df = data['graph'].apply(lambda x: (x.get("step1")))
data['graph'] = df

data = data.assign(query_type = lambda x: (x['meta']))
df = data['query_type'].apply(lambda x: (x.get("query_type")))
data['query_type'] = df

data = data.assign(info = lambda x: (x['meta']))
df = data['info'].apply(lambda x: (x.get("given_info")))
data['info'] = df

data = data.assign(graph_type = lambda x: (x['meta']))
df = data['graph_type'].apply(lambda x: (x.get("graph_id")))
data['graph_type'] = df
data

,question_id,desc_id,given_info,question,answer,meta,reasoning,formal_form,graph,query_type,info,graph_type
0,4,alarm-mediation-nde-model0-spec0-q0,For husbands that don't set the alarm and wive...,If we disregard the mediation effect through w...,yes,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...,"E[Y_{X=1, V2=0} - Y_{X=0, V2=0}]","X->V2,X->Y,V2->Y",nde,"{'p(Y | X, V2)': [[0.08430222457648501, 0.5394...",mediation
1,7,alarm-mediation-ate-model1-spec1-q1,"For husbands that don't set the alarm, the pro...",Will alarm set by husband decrease the chance ...,no,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...,E[Y | do(X = 1)] - E[Y | do(X = 0)],"X->V2,X->Y,V2->Y",ate,"{'p(Y | X)': [0.26076060984306904, 0.755829649...",mediation
2,8,alarm-mediation-marginal-model1-spec1-q0,The overall probability of alarm set by husban...,Is ringing alarm more likely than silent alarm...,yes,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...,P(Y),"X->V2,X->Y,V2->Y",marginal,"{'P(X)': 0.771884206668314, 'P(Y | X)': [0.260...",mediation
3,15,alarm-mediation-ate-model3-spec3-q1,"For husbands that don't set the alarm, the pro...",Will alarm set by husband decrease the chance ...,no,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...,E[Y | do(X = 1)] - E[Y | do(X = 0)],"X->V2,X->Y,V2->Y",ate,"{'p(Y | X)': [0.19568691380685402, 0.683664327...",mediation
4,21,alarm-mediation-nie-model4-spec4-q0,For husbands that don't set the alarm and wive...,Does husband positively affect alarm clock thr...,no,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...,"E[Y_{X=0, V2=1} - Y_{X=0, V2=0}]","X->V2,X->Y,V2->Y",nie,"{'p(Y | X, V2)': [[0.107877091110262, 0.602626...",mediation
...,...,...,...,...,...,...,...,...,...,...,...,...
8527,31012,nonsense9-fork-det-counterfactual-model3842-sp...,We know that zuph or jyka causes glimx. We obs...,Would an individual is glimx if not zuph inste...,yes,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....,Y_{X=0} = 1 | V2=1,"X->Y,V2->Y",det-counterfactual,{'V2': 1},fork
8528,31014,nonsense9-fork-det-counterfactual-model3842-sp...,We know that zuph or jyka causes glimx. We obs...,Would an individual is glimx if zuph instead o...,yes,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....,Y_{X=1} = 1 | V2=1,"X->Y,V2->Y",det-counterfactual,{'V2': 1},fork
8529,31015,nonsense9-fork-det-counterfactual-model3842-sp...,We know that zuph or jyka causes glimx. We obs...,Would an individual is not glimx if zuph inste...,no,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....,Y_{X=1} = 0 | V2=1,"X->Y,V2->Y",det-counterfactual,{'V2': 1},fork
8530,31016,nonsense9-fork-det-counterfactual-model3843-sp...,We know that zuph and jyka causes glimx. We ob...,Would an individual is glimx if not zuph inste...,no,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....,Y_{X=0} = 1 | V2=0,"X->Y,V2->Y",det-counterfactual,{'V2': 0},fork
8531,31019,nonsense9-fork-det-counterfactual-model3843-sp...,We know that zuph and jyka causes glimx. We ob...,Would an individual is not glimx if zuph inste...,yes,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....,Y_{X=1} = 0 | V2=0,"X->Y,V2->Y",det-counterfactual,{'V2': 0},fork

In [2]:
import pandas as pd
data = pd.read_json('cladder.json')
data = data.dropna().reset_index(drop=True)
data

,question_id,desc_id,given_info,question,answer,meta,reasoning
0,4,alarm-mediation-nde-model0-spec0-q0,For husbands that don't set the alarm and wive...,If we disregard the mediation effect through w...,yes,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...
1,7,alarm-mediation-ate-model1-spec1-q1,"For husbands that don't set the alarm, the pro...",Will alarm set by husband decrease the chance ...,no,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...
2,8,alarm-mediation-marginal-model1-spec1-q0,The overall probability of alarm set by husban...,Is ringing alarm more likely than silent alarm...,yes,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...
3,15,alarm-mediation-ate-model3-spec3-q1,"For husbands that don't set the alarm, the pro...",Will alarm set by husband decrease the chance ...,no,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...
4,21,alarm-mediation-nie-model4-spec4-q0,For husbands that don't set the alarm and wive...,Does husband positively affect alarm clock thr...,no,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...
...,...,...,...,...,...,...,...
8527,31012,nonsense9-fork-det-counterfactual-model3842-sp...,We know that zuph or jyka causes glimx. We obs...,Would an individual is glimx if not zuph inste...,yes,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....
8528,31014,nonsense9-fork-det-counterfactual-model3842-sp...,We know that zuph or jyka causes glimx. We obs...,Would an individual is glimx if zuph instead o...,yes,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....
8529,31015,nonsense9-fork-det-counterfactual-model3842-sp...,We know that zuph or jyka causes glimx. We obs...,Would an individual is not glimx if zuph inste...,no,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....
8530,31016,nonsense9-fork-det-counterfactual-model3843-sp...,We know that zuph and jyka causes glimx. We ob...,Would an individual is glimx if not zuph inste...,no,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....
8531,31019,nonsense9-fork-det-counterfactual-model3843-sp...,We know that zuph and jyka causes glimx. We ob...,Would an individual is not glimx if zuph inste...,yes,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....

In [4]:
#exchange "formal_form" and "graph" column's variables to their respective "true name" (ex: exchange X to husband, V2 to wife, etc)
def exchange(x, form, aux):
    x = x.get('step0')
    if(aux == 1):
        form = form.get('formal_form')
    elif(aux == 0):
        form = form.get('step1')
    else:
        form = str(form)
    
    x = x[4:len(x)-1] #erase "Let " and the last "."
    x = x.split('; ')

    for i in range(len(x)):
        aux = x[i].split(" = ")
        form = form.replace(aux[0],aux[1])
    return form


#exchange query_type abbreviation to the whole word

def expand(abb):
    if abb == 'nde':
        return 'natural direct effect'
    elif abb == 'ate':
        return 'average treatment effect'
    elif abb == 'marginal':
        return 'marginal probability'
    elif abb == 'nie':
        return 'natural indirect effect'
    elif abb == 'det-counterfactual':
        return 'normal counterfactual question'
    elif abb == 'ett':
        return 'average treatment effect on treated'
    elif abb == 'correlation':
        return 'conditional probability'
    elif abb == 'exp_away':
        return 'explaining away effect'
    elif abb == 'collider_bias':
        return 'collider bias'
    elif abb == 'backadj':
        return 'backdoor adjustment set'
    return 0
    

#data['formal_form'] = data.apply(lambda x: exchange(x['reasoning'], x['meta'],1), axis=1)
#data['graph'] = data.apply(lambda x: exchange(x['reasoning'], x['reasoning'],0), axis=1)
#data['info'] = data.apply(lambda x: exchange(x['reasoning'], x['info'],2), axis=1)
data['query_type'] = data.apply(lambda x: expand(x['query_type']), axis=1)

data

,question_id,desc_id,given_info,question,answer,meta,reasoning,formal_form,graph,query_type,info,graph_type
0,4,alarm-mediation-nde-model0-spec0-q0,For husbands that don't set the alarm and wive...,If we disregard the mediation effect through w...,yes,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...,"E[Y_{X=1, V2=0} - Y_{X=0, V2=0}]","X->V2,X->Y,V2->Y",natural direct effect,"{'p(Y | X, V2)': [[0.08430222457648501, 0.5394...",mediation
1,7,alarm-mediation-ate-model1-spec1-q1,"For husbands that don't set the alarm, the pro...",Will alarm set by husband decrease the chance ...,no,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...,E[Y | do(X = 1)] - E[Y | do(X = 0)],"X->V2,X->Y,V2->Y",average treatment effect,"{'p(Y | X)': [0.26076060984306904, 0.755829649...",mediation
2,8,alarm-mediation-marginal-model1-spec1-q0,The overall probability of alarm set by husban...,Is ringing alarm more likely than silent alarm...,yes,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...,P(Y),"X->V2,X->Y,V2->Y",marginal probability,"{'P(X)': 0.771884206668314, 'P(Y | X)': [0.260...",mediation
3,15,alarm-mediation-ate-model3-spec3-q1,"For husbands that don't set the alarm, the pro...",Will alarm set by husband decrease the chance ...,no,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...,E[Y | do(X = 1)] - E[Y | do(X = 0)],"X->V2,X->Y,V2->Y",average treatment effect,"{'p(Y | X)': [0.19568691380685402, 0.683664327...",mediation
4,21,alarm-mediation-nie-model4-spec4-q0,For husbands that don't set the alarm and wive...,Does husband positively affect alarm clock thr...,no,"{'story_id': 'alarm', 'graph_id': 'mediation',...",{'step0': 'Let X = husband; V2 = wife; Y = ala...,"E[Y_{X=0, V2=1} - Y_{X=0, V2=0}]","X->V2,X->Y,V2->Y",natural indirect effect,"{'p(Y | X, V2)': [[0.107877091110262, 0.602626...",mediation
...,...,...,...,...,...,...,...,...,...,...,...,...
8527,31012,nonsense9-fork-det-counterfactual-model3842-sp...,We know that zuph or jyka causes glimx. We obs...,Would an individual is glimx if not zuph inste...,yes,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....,Y_{X=0} = 1 | V2=1,"X->Y,V2->Y",normal counterfactual question,{'V2': 1},fork
8528,31014,nonsense9-fork-det-counterfactual-model3842-sp...,We know that zuph or jyka causes glimx. We obs...,Would an individual is glimx if zuph instead o...,yes,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....,Y_{X=1} = 1 | V2=1,"X->Y,V2->Y",normal counterfactual question,{'V2': 1},fork
8529,31015,nonsense9-fork-det-counterfactual-model3842-sp...,We know that zuph or jyka causes glimx. We obs...,Would an individual is not glimx if zuph inste...,no,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....,Y_{X=1} = 0 | V2=1,"X->Y,V2->Y",normal counterfactual question,{'V2': 1},fork
8530,31016,nonsense9-fork-det-counterfactual-model3843-sp...,We know that zuph and jyka causes glimx. We ob...,Would an individual is glimx if not zuph inste...,no,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....,Y_{X=0} = 1 | V2=0,"X->Y,V2->Y",normal counterfactual question,{'V2': 0},fork
8531,31019,nonsense9-fork-det-counterfactual-model3843-sp...,We know that zuph and jyka causes glimx. We ob...,Would an individual is not glimx if zuph inste...,yes,"{'story_id': 'nonsense9', 'graph_id': 'fork', ...",{'step0': 'Let V2 = jyka; X = zuph; Y = glimx....,Y_{X=1} = 0 | V2=0,"X->Y,V2->Y",normal counterfactual question,{'V2': 0},fork

In [6]:
a['question'][200]

'Will smoking decrease the chance of lung cancer?'

In [16]:
pd.set_option('display.max_colwidth', None)

In [27]:
a = data[data['query_type'] == 'average treatment effect'].reset_index(drop=True)

In [34]:
a = data[data['query_type'] == 'average treatment effect'].reset_index(drop=True)
a = a[a['graph_type'] == 'IV'].reset_index(drop=True)
a['reasoning'].iloc[100]
#a

{'step0': 'Let V2 = proximity to a college; V1 = unobserved confounders; X = education level; Y = foot size.',
 'step1': 'V1->X,V2->X,V1->Y,X->Y',
 'step2': 'E[Y | do(X = 1)] - E[Y | do(X = 0)]',
 'step3': '[P(Y=1|V2=1)-P(Y=1|V2=0)]/[P(X=1|V2=1)-P(X=1|V2=0)]',
 'step4': 'P(Y=1 | V2=0) = 0.45\nP(Y=1 | V2=1) = 0.63\nP(X=1 | V2=0) = 0.39\nP(X=1 | V2=1) = 0.13',
 'step5': '(0.63 - 0.45) / (0.13 - 0.39) = -0.69',
 'end': '-0.69 < 0'}

In [14]:
#marginal probability
def marg_prob(P_X, P_Y_X):
    PY = 0
    for i in range(len(P_X)):
        PY += P_X[i]*P_Y_X[i]
    return PY

#natural direct effect
def NDE(graph, P_V2_X0, P_Y1_V2_X):
    #P_Y1_V2_X = [[x0v0,x1v0],[x0v1,x1v1]]
    #P_V2_X0 = [v0x0,v1x0]

    #v2 and v3 may be different
    if(graph == 'X->V3,V2->V3,X->Y,V2->Y,V3->Y'): #'graph_id': arrowhead
        nde = 
    elif(graph == 'X->V2,X->Y,V2->Y'): #'graph_id': 'mediation'
        nde = P_V2_X0[0]*(P_Y1_V2_X[0][1] - P_Y1_V2_X[0][0]) + P_V2_X0[1]*(P_Y1_V2_X[1][1] - P_Y1_V2_X[1][0])
    
    return nde

def ATE():

    if(graph == 'V1->X,V2->X,V1->Y,X->Y'): #'graph_id': 'IV'
        ate = ( P(Y=1|V2=1)-P(Y=1|V2=0) )/( P(X=1|V2=1)-P(X=1|V2=0) )

In [ ]:
IV
arrowhead
chain
collision
confounding
diamond
diamondcut
fork
frontdoor
mediation